#!/usr/bin/env bash

# Enable extra bash_completion, if installed
if [ -f /opt/local/etc/bash_completion ] && ! shopt -oq posix; then
    . /opt/local/etc/bash_completion
fi

# Enable rvm (Ruby version manager)
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    source "$HOME/.rvm/scripts/rvm"
fi