#!/usr/bin/env bash
# History configuration

export HISTSIZE=100000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignorespace:ignoredups

function history {
    _bash_history_sync
    builtin history "$@"
}

function _bash_history_sync {
    builtin history -a
    HISTFILESIZE=$HISTFILESIZE
    builtin history -c
    builtin history -r
}

export PROMPT_COMMAND="_bash_history_sync; $PROMPT_COMMAND"
