#!/usr/bin/env bash
# PATH configuration

declare -a all_paths=(
    /opt/local/bin /opt/local/sbin
    /usr/local/bin /usr/local/sbin
    /usr/X11R6/bin
    /bin /sbin /usr/bin /usr/sbin
    $(command -p getconf PATH | sed 's/:/ /g')	# System path
    ${HOME}/bin    
)

unset PATH_tmp
for path in ${all_paths[@]}; do
    if [[ $(expr "$PATH_tmp" : ".*:$path:.*") -eq 0 ]]; then
	if [[ -d "$path" ]]; then
	    PATH_tmp="${PATH_tmp}${path}:"
	fi
    fi
done

export PATH=$PATH_tmp
