#!/usr/bin/env bash

# Configure colors:
function fg_reset { 
	echo '\e[0m'; 
}

colors="black red green yellow blue purple cyan white"
i=30
for color in $colors; do 
	for j in {0..1}; do
		style=`[ $j = 0 ] && echo "" || echo bold`
		fname=`[ -z $style ] && echo fg_$color || echo fg_${style}_${color}`
		fun=`echo 'function' "$fname" '{
			[ -z $1 ] && return 1;
			echo -e "\e['"$j;${i}m"'$1'"$(fg_reset)"'";
		}'`
		eval $fun
	done
	i=$((i+1))
done

# Usage: 
# $ fg_green "text"
# [0;32mtext[0m

function promptcmd {
	# Define left and right prompts
	curdir=$(pwd | sed -e "s,^$HOME,~,")
	user=$(id -un)
	host=$(hostname)
	left="$user at $host in" # curdir
	right="$(date +%H:%M)"
	
	cols=`stty size | cut -d' ' -f2` 
	
	# Change the length of curdir according to $COLUMNS
	len=$(echo "$left $curdir $right" | wc -c)
	if [ $len -gt $cols ]; then
		curdir="...${curdir:$(($len-$cols+2))}"
	fi
	# Move the right prompt to the right side
	len=$(echo "$left $curdir $right" | wc -c)
	right=$(fg_cyan $right)
	if [ $len -lt $cols ]; then
		right=$(printf "%$(($cols-$len+1))s${right}" "")
	fi
	# Add colors
	user=$(fg_purple $user)
	host=$(fg_yellow $host)
	curdir=$(fg_red $curdir)
	left="$user at $host in $curdir"
	# Export
	# export PS1="\[\e[1;32m\]$left $curdir $right\n$\[\e[0m\] "
	# export PS1="\[\e[1;32m\][$user@$host \W]\$\[\e[0m\] "
	echo -e "$left $right"
}

export PS1="$ "
export PROMPT_COMMAND=promptcmd

# Resize handler
# function resized_window {
# 	out=""
# 	# Save the cursor position
# 	out="$out\e[s"
# 	# Go to the line above the prompt (handle multiple lines?)
# 	out="$out\e[1A"
# 	# Go to the beginning of the line
# 	out="$out\e[${COLUMNS}D"
# 	# Clear the contents of the line
# 	out="$out\e[K"
# 	# Re-echo the prompt
# 	out="$out$(promptcmd)"
# 	# Restore the cursor position
# 	out="$out\e[u\e[2C"
# 	
# 	echo -e "$out"
# }
# 
# trap resized_window SIGWINCH
