#!/usr/bin/env bash

# Configure colors:
function fg_reset { 
    echo '\x1B[0m'; 
}

colors="black red green yellow blue purple cyan white"
i=30
for color in $colors; do 
    for j in {0..1}; do
	style=`[ $j = 0 ] && echo "" || echo bold`
	fname=`[ -z $style ] && echo fg_$color || echo fg_${style}_${color}`
	fun=`echo 'function' "$fname" '{
	    [ -z "$1" ] && return 1;
	    echo -e "\x1B['"$j;${i}m"'"$1"'"$(fg_reset)"'";
	    }'`
	eval $fun
    done
    i=$((i+1))
done

# Usage: 
# $ fg_green "text"
# [0;32mtext[0m

function promptcmd {
    # Define left and right prompts
    curdir=$(pwd | sed -e "s,^$HOME,~,")
    user=$(id -un)
    host=$(hostname)
    left="$user at $host in" # curdir
    right="$(date +%H:%M)"
    
    cols=`stty size | cut -d' ' -f2` 
    
    # Change the length of curdir according to $cols
    len=$(echo "$left $curdir $right" | wc -c)
    if [ $len -gt $cols ]; then
	elip=$(echo -e "\xe2\x80\xa6")
	curdir="${elip}${curdir:$(($len-$cols))}"
    fi

    # Move the right prompt to the right side
    len=$(echo "$left $curdir $right" | wc -c)
    right=$(fg_cyan $right)
    if [ $len -lt $cols ]; then
	right=$(printf "%$(($cols-$len+1))s${right}" "")
    fi

    # Add colors
    user=$(fg_purple $user)
    host=$(fg_yellow $host)
    curdir=$(fg_green "$curdir")
    left="$user at $host in $curdir"
    # Export
    # export PS1="\[\x1B[1;32m\]$left $curdir $right\n$\[\x1B[0m\] "
    # export PS1="\[\x1B[1;32m\][$user@$host \W]\$\[\x1B[0m\] "
    echo -e "$left $right"
}

export PS1="$ "
export PROMPT_COMMAND="promptcmd"

# Resize handler
function resized_window {
    cols=$(stty size)
    echo -e "\x1B[1A\x1B[${cols}D\x1B[K$(promptcmd)"
}

# Not working yet
# trap resized_window SIGWINCH
